# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a142f1a9a70df12f03c00886b1b348708337540075ef25f852215cc4c6dbf11e428b8d6d865b586ed3a8469d72252676d4a3653d536c05a32a0f3044095c6fc

test:
  secret_key_base: 672129e4001b8f46db7ed34a0d5834b9d8b5b0e532a283732f9f51e4235579e3e0c210167799b311e02f58570390e017fa308d44be2257eebb18cfa293d5f584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
